### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by notflip** [eliyas5044/laravel-api#1]
Thanks for this repo! I'm wondering how Authentication works, if any?

**Comment by eliyas5044** [comment]
Thanks for your comment. You should you Laravel Passport for api authentication. It use OAuth2.

**Comment by eliyas5044** [comment]
@notflip finally, i added api authentication by `laravel passport`, check it out.

**Comment by notflip** [comment]
Great! Thanks for the update!
